const types = {
  SET_USER: 'SET_USER',
  SET_USER_ERROR: 'SET_USER_ERROR',
  GOOGLE_SIGNIN_SUCCESS: 'GOOGLE_SIGNIN_SUCCESS',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
};

export default types;
